/* OpenRG: This file was automatically generated by pkg/build/create_config 
 * See /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/build.FAST3202_LBV2ULT/config.log for configuration log.
 */

#define AUTOCONF_INCLUDED
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:22 */
#define cCONFIG_SAGEM_WITH_HARDWARE_WATCHDOG_ADI 1
#define CONFIG_SAGEM_WITH_HARDWARE_WATCHDOG_ADI 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:50 */
#define CONFIG_INOTIFY 1

#define cCONFIG_RG_DEV_IF_ATHBCMWRAPPER 0

#define cCONFIG_RG_DEV_IF_BCM43XX 0

#define cCONFIG_RG_DEV_IF_AR500XX 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1582 */
#define CONFIG_RG_DEV_IF_VLAN 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1654 */
#define CONFIG_RG_DEV_IF_ETHOA 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/device_config.c:193 */
#define CONFIG_RG_DEV_IF_BRIDGE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1518 */
#define CONFIG_RG_DEV_IF_AD6834_ETH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1639 */
#define CONFIG_RG_DEV_IF_AD68XX_ADSL 1

#define cCONFIG_RG_DEV_IF_HSDPA 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3268 */
#define cCONFIG_BOOTLDR_UBOOT 1
#define CONFIG_BOOTLDR_UBOOT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2971 */
#define RG_PROD_STR "Livebox"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:40 */
#define CONFIG_RG_OS "LINUX_26"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:206 */
#define cCONFIG_RG_HW "FAST3202"
#define CONFIG_RG_HW "FAST3202"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:207 */
#define cCONFIG_RG_HW_DESC_STR "Sagem F@ST3202 Livebox1"
#define CONFIG_RG_HW_DESC_STR "Sagem F@ST3202 Livebox1"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:5054 */
#define cCONFIG_RG_DIST "FAST3202_LBV2ULT"
#define CONFIG_RG_DIST "FAST3202_LBV2ULT"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3240 */
#define cCONFIG_RG_WBM_READONLY_USERS_GROUPS 1
#define CONFIG_RG_WBM_READONLY_USERS_GROUPS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:95 */
#define CONFIG_MMU 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:68 */
#define CONFIG_INIT_ENV_ARG_LIMIT 32
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:71 */
#define CONFIG_PRINTK 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:73 */
#define CONFIG_BUG 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:74 */
#define CONFIG_TINY_SHMEM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:75 */
#define CONFIG_BASE_SMALL 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:101 */
#define CONFIG_OBSOLETE_MODPARM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:102 */
#define CONFIG_KMOD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:76 */
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:118 */
#define CONFIG_IOSCHED_NOOP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:96 */
#define CONFIG_DEFAULT_IOSCHED "anticipatory"

#define cCONFIG_NET_IPGRE_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1234 */
#define CONFIG_XFRM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1235 */
#define CONFIG_CRYPTO 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1236 */
#define CONFIG_CRYPTO_HMAC 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1237 */
#define CONFIG_CRYPTO_MD5 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1238 */
#define CONFIG_CRYPTO_SHA1 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1239 */
#define CONFIG_CRYPTO_AES 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1240 */
#define CONFIG_INET_AH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:115 */
#define CONFIG_NET_SCH_CLK_JIFFIES 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:124 */
#define CONFIG_LEGACY_PTYS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:125 */
#define CONFIG_LEGACY_PTY_COUNT 256
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1195 */
#define CONFIG_LOG_BUF_SHIFT 14
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:93 */
#define CONFIG_CRC32 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:77 */
#define CONFIG_GENERIC_HARDIRQS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:114 */
#define CONFIG_IP_MULTIPLE_TABLES 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:100 */
#define CONFIG_MODULE_UNLOAD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1177 */
#define CONFIG_BOOT_ELF32 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1191 */
#define CONFIG_DMA_NONCOHERENT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3255 */
#define cCONFIG_SOFTIRQ_THROTTLE 1
#define CONFIG_SOFTIRQ_THROTTLE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1250 */
#define CONFIG_KALLSYMS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1193 */
#define CONFIG_MIPS_L1_CACHE_SHIFT 5
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1231 */
#define CONFIG_DEBUG_INFO 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1194 */
#define CONFIG_PAGE_SIZE_4KB 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1192 */
#define CONFIG_TRAD_SIGNALS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2545 */
#define CONFIG_INITRAMFS_SOURCE $(RAMDISK_MOUNT_POINT)
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2546 */
#define CONFIG_INITRAMFS_ROOT_UID $(shell id -u)
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2547 */
#define CONFIG_INITRAMFS_ROOT_GID $(shell id -g)
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:111 */
#define CONFIG_IP_FIB_HASH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1169 */
#define ARCH "mips"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1170 */
#define LIBC_ARCH mips

#define cCONFIG_BRIDGE_FEATURE 0

#define cCONFIG_BRIDGE_UTILS 0

#define cCONFIG_IPTABLES 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:575 */
#define CONFIG_NETFILTER 1

#define cCONFIG_IP_NF_FILTER_FEATURE 0

#define cCONFIG_IP_NF_IPTABLES_FEATURE 0

#define cCONFIG_IP_NF_CONNTRACK_FEATURE 0

#define cCONFIG_IP_NF_NAT_FEATURE 0

#define cCONFIG_IP_NF_TARGET_MASQUERADE_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3061 */
#define CONFIG_EXPORT_BINARIES 1

#define cCONFIG_LSP_DIST 0

#define cCONFIG_RG_RGLOADER 0

#define cCONFIG_RG_NETWORK_BOOT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:299 */
#define CONFIG_RG_RGLOADER_CLI_CMD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1828 */
#define CONFIG_RG_UIEVENTS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1829 */
#define cCONFIG_RG_KLEDS_FEATURE 1
#define CONFIG_RG_KLEDS_FEATURE 1
#define CONFIG_RG_KLEDS_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1831 */
#define cCONFIG_RG_KSTART_LEDS_LUMS_FEATURE 1
#define CONFIG_RG_KSTART_LEDS_LUMS_FEATURE 1
#define CONFIG_RG_KSTART_LEDS_LUMS_MODULE 1

#define cCONFIG_RG_KRGLDR_FEATURE 0

#define cCONFIG_RG_KMONTE 0

#define cCONFIG_PCMCIA 0
#define cCONFIG_PCMCIA_FEATURE 0

#define cCONFIG_80211G_AP_ADVANCED 0

#define cCONFIG_80211_WDS 0

#define cCONFIG_8139TOO_FEATURE 0

#define cCONFIG_ARCH_IXP22X 0

#define cCONFIG_ARCH_IXP425_HG21 0

#define cCONFIG_ARCH_IXP425_NAPA 0

#define cCONFIG_ARCH_IXP425_BAMBOO 0

#define cCONFIG_ARCH_IXP425_JEEVES 0

#define cCONFIG_JEEVES_RTC7301_FEATURE 0

#define cCONFIG_ARCH_IXP425_WAV54G 0

#define cCONFIG_ARCH_IXP425_BRUCE 0

#define cCONFIG_ARCH_IXP425_BRUCE_CPLD_FEATURE 0

#define cCONFIG_ARM 0

#define cCONFIG_ARMNOMMU 0

#define cCONFIG_ATALK_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:424 */
#define cCONFIG_ATM 1
#define CONFIG_ATM 1

#define cCONFIG_ATM_NULL 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:426 */
#define cCONFIG_ATM_BR2684_FEATURE 1
#define CONFIG_ATM_BR2684_FEATURE 1
#define CONFIG_ATM_BR2684 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:433 */
#define cCONFIG_ATM_CLIP_FEATURE 1
#define CONFIG_ATM_CLIP_FEATURE 1
#define CONFIG_ATM_CLIP_MODULE 1

#define cCONFIG_ATM_CONEXANT_DSL_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:425 */
#define CONFIG_ATM_SKB 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:429 */
#define cCONFIG_ATM_PVC_SCAN 1
#define CONFIG_ATM_PVC_SCAN 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1635 */
#define cCONFIG_RG_ATM_QOS 1
#define CONFIG_RG_ATM_QOS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:214 */
#define cCONFIG_AUTO_LEARN_DNS 1
#define CONFIG_AUTO_LEARN_DNS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:80 */
#define cCONFIG_BINFMT_ELF_FEATURE 1
#define CONFIG_BINFMT_ELF_FEATURE 1
#define CONFIG_BINFMT_ELF 1

#define cCONFIG_BLK_DEV_IDE_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1100 */
#define CONFIG_CMDLINE "console=ttyS0,57600 quiet"

#define cCONFIG_CNXT_EMAC_FEATURE 0

#define cCONFIG_CNXT_ADSL_FEATURE 0

#define cCONFIG_CNXT_ATM_FEATURE 0

#define cCONFIG_CNXT_SOFTSAR_FEATURE 0

#define cCONFIG_CONEXANT_DSL_TIGRIS_FEATURE 0

#define cCONFIG_CONEXANT_DSL_YUKON_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2567 */
#define CONFIG_CRAMFS_DYN_BLOCKSIZE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2582 */
#define CONFIG_CRAMFS_BLKSZ 65536
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1171 */
#define CONFIG_CPU_BIG_ENDIAN 1

#define cCONFIG_ROMFS_FS 0

#define cCONFIG_RG_BZIP2 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2563 */
#define CONFIG_CRAMFS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2551 */
#define CONFIG_CRAMFS_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:123 */
#define CONFIG_NTFS_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2561 */
#define cCONFIG_CRAMFS_FS_COMMON 1
#define CONFIG_CRAMFS_FS_COMMON 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1201 */
#define CONFIG_CROSSCOMPILE 1

#define cCONFIG_CX821XX_COMMON 0

#define cCONFIG_GEMTEK_WX5715 0

#define cCONFIG_ISL38XX_FEATURE 0

#define cCONFIG_ISL_SOFTMAC_FEATURE 0

#define cCONFIG_RALINK_RT2560_FEATURE 0

#define cCONFIG_AGN100_FEATURE 0

#define cCONFIG_WIRELESS_TOOLS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:144 */
#define cCONFIG_RG_WIRELESS_EXTENSIONS 1
#define CONFIG_RG_WIRELESS_EXTENSIONS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:874 */
#define CONFIG_DEF_KEYS 1

#define cCONFIG_DSL_SYNCD_FEATURE 0

#define cCONFIG_DUETTE_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1204 */
#define CONFIG_DYN_LINK 1

#define cCONFIG_EEPRO100_FEATURE 0

#define cCONFIG_EEXPRESS_PRO100_FEATURE 0
/* Set by command line */
#define LIC /home/p778094/devbis/kernel/4.3.14/lastcheckout/license/jpkg_fast3202.lic
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/create_config.c:655 */
#define LICSTR 34ab8923211d0b2de5d3d0b527e8e204cf095886cdab51635b07f7222b565eb03491a37a19864f125d3bf8b5838ce291e6cc9907678ec674b5d1cee0a0fbd19115f3bd3d3a0ee7f89b9af02f

#define cCONFIG_LICENSE_AGREEMENT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:51 */
#define CONFIG_E2FSPROGS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2859 */
#define CONFIG_DOSFSPROGS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2860 */
#define CONFIG_EXT2_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:124 */
#define CONFIG_EXT3_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:125 */
#define CONFIG_JBD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1103 */
#define CONFIG_MAGIC_SYSRQ 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1494 */
#define CONFIG_FREEPAGES_HIGH 384
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1493 */
#define CONFIG_FREEPAGES_LOW 256
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1492 */
#define CONFIG_FREEPAGES_MIN 32
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3079 */
#define CONFIG_FREEPAGES_THRESHOLD 1

#define cCONFIG_FREESWAN 0

#define cCONFIG_RG_NETBIOS_RT_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1483 */
#define CONFIG_GEN_RG_DEFAULT 1

#define cCONFIG_GLIBC 0

#define cCONFIG_GMP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1166 */
#define CONFIG_HAS_MMU 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/device_config.c:203 */
#define cCONFIG_DEF_BRIDGE_LANS 1
#define CONFIG_DEF_BRIDGE_LANS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/device_config.c:205 */
#define cCONFIG_DEF_BRIDGE_WAN 1
#define CONFIG_DEF_BRIDGE_WAN 1

#define cCONFIG_DEF_WAN_BRIDGE_FALLBACK_IP 0

#define cCONFIG_DEF_BRIDGE_ALTERNATE_IP 0

#define cCONFIG_DEF_WAN_ALIAS_IP 0

#define cCONFIG_IEEE1394_FEATURE 0

#define cCONFIG_IEEE1394_OHCI1394_FEATURE 0

#define cCONFIG_IEEE1394_ETH1394_FEATURE 0

#define cCONFIG_IEEE1394_SBP2_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:109 */
#define cCONFIG_INET_FEATURE 1
#define CONFIG_INET_FEATURE 1
#define CONFIG_INET 1

#define cCONFIG_INIT_BASIC_RUNLEVELS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:612 */
#define CONFIG_IP_ADVANCED_ROUTER 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:110 */
#define cCONFIG_IP_MULTICAST 1
#define CONFIG_IP_MULTICAST 1

#define cCONFIG_IPSEC 0

#define cCONFIG_IPSEC_ALG_MD5_FEATURE 0

#define cCONFIG_IPSEC_ALG_SHA1_FEATURE 0

#define cCONFIG_IPSEC_ALG_3DES_FEATURE 0

#define cCONFIG_IPSEC_ALG_1DES_FEATURE 0

#define cCONFIG_IPSEC_ALG_NULL_FEATURE 0

#define cCONFIG_IPSEC_ENC_AES 0

#define cCONFIG_IPSEC_ALG_AES_FEATURE 0

#define cCONFIG_IPSEC_DRIVER_FEATURE 0

#define cCONFIG_IXP_CS8900_FEATURE 0

#define cCONFIG_ARCH_IXP425 0

#define cCONFIG_IXP425_CODELET_DSP_ENG_FEATURE 0

#define cCONFIG_IXP425_CODELET_ATM_FEATURE 0

#define cCONFIG_IXP425_CODELET_ETH_FEATURE 0

#define cCONFIG_IXP425_CODELET_HSS_FEATURE 0

#define cCONFIG_IXP425_CODELET_USB_FEATURE 0

#define cCONFIG_IXP425_CODELET_DMA_FEATURE 0

#define cCONFIG_IXP425_CODELET_CRYPTO_FEATURE 0

#define cCONFIG_IXP425_CODELET_PERF_PROF_FEATURE 0

#define cCONFIG_IXP425_CODELET_TIMERS_FEATURE 0

#define cCONFIG_IXP425_CODELETS_FEATURE 0

#define cCONFIG_IXP425_COMMON 0

#define cCONFIG_IXP425_CSR_FEATURE 0

#define cCONFIG_IXP425_DSR_FEATURE 0

#define cCONFIG_IXP425_ETH_FEATURE 0

#define cCONFIG_IXP425_ATM_FEATURE 0

#define cCONFIG_IXP425_FLASH_E28F128J3_FEATURE 0

#define cCONFIG_IXP425_FLASH_E28F640J3_FEATURE 0

#define cCONFIG_IXP425_FLASH_E28F320J3_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1837 */
#define cCONFIG_JFFS2_FS_FEATURE 1
#define CONFIG_JFFS2_FS_FEATURE 1
#define CONFIG_JFFS2_FS 1

#define cCONFIG_LINUX_OAM_FEATURE 0

#define cCONFIG_LOCKD_FEATURE 0

#define cCONFIG_I2C_FEATURE 0

#define cCONFIG_I2C_ALGOBIT_FEATURE 0

#define cCONFIG_I2C_IXP425_FEATURE 0

#define cCONFIG_I2C_DS1374_FEATURE 0

#define cCONFIG_I2C_LM81_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2763 */
#define CONFIG_LOG_FILES_MAX_SIZE 16384
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2762 */
#define CONFIG_LOG_FILES_MIN_SIZE 12288
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_host.c:1371 */
#define cCONFIG_MIPS 1
#define CONFIG_MIPS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1175 */
#define CONFIG_MIPS_PATENTFREE 1

#define cCONFIG_RG_INSMOD_SILENT 0

#define cCONFIG_INCAIP 0

#define cCONFIG_INCAIP_KEYPAD_FEATURE 0

#define cCONFIG_INCAIP_LEDMATRIX_FEATURE 0

#define cCONFIG_INCAIP_DSP_FEATURE 0

#define cCONFIG_VINETIC_FEATURE 0

#define cCONFIG_INCAIP_IOM2_FEATURE 0

#define cCONFIG_INCAIP_ETHERNET_FEATURE 0

#define cCONFIG_INCAIP_PSEUDO_LAN_FEATURE 0

#define cCONFIG_INCAIPSSC_FEATURE 0

#define cCONFIG_INCAIPPWM_FEATURE 0

#define cCONFIG_SERIAL_INCAIPASC_FEATURE 0

#define cCONFIG_MTD_INCAIP_FEATURE 0

#define cCONFIG_ZSP400_FEATURE 0

#define cCONFIG_INCAIP_SWITCH_FEATURE 0

#define cCONFIG_INCAIP_SWITCH_API_FEATURE 0

#define cCONFIG_MPC8272ADS 0

#define cCONFIG_ADM5120_COMMON 0

#define cCONFIG_ADM5120_MTD_FEATURE 0

#define cCONFIG_ADM5120_SWITCH_FEATURE 0

#define cCONFIG_ET_FEATURE 0

#define cCONFIG_BCM947XX 0

#define cCONFIG_BCM947_COMMON 0

#define cCONFIG_BCM963XX 0

#define cCONFIG_BCM963XX_MTD_FEATURE 0

#define cCONFIG_BCM963XX_SERIAL_FEATURE 0

#define cCONFIG_BCM963XX_BOARD_FEATURE 0

#define cCONFIG_BCM963XX_ETH_FEATURE 0

#define cCONFIG_BCM963XX_ATM_FEATURE 0

#define cCONFIG_BCM963XX_ADSL_FEATURE 0

#define cCONFIG_BCM963XX_USB_FEATURE 0

#define cCONFIG_BCM963XX_WLAN_FEATURE 0

#define cCONFIG_BCM963XX_ENDPOINT_FEATURE 0

#define cCONFIG_BCM963XX_PROCFS_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1097 */
#define cCONFIG_CPU_LX4189 1
#define CONFIG_CPU_LX4189 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1161 */
#define cCONFIG_ADI_6843 1
#define CONFIG_ADI_6843 1

#define cCONFIG_ETH_NETPRO_SIERRA_FEATURE 0

#define cCONFIG_ADI_6843_USB_FEATURE 0

#define cCONFIG_ADI_6843_MTD_FEATURE 0

#define cCONFIG_ADI_6843_UART2_FEATURE 0

#define cCONFIG_DSPDRIVER_218X_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1631 */
#define CONFIG_MACH_ADI_FUSIV 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1843 */
#define cCONFIG_FUSIV_LIBRARY 1
#define CONFIG_FUSIV_LIBRARY 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1844 */
#define cCONFIG_FUSIV_BMDRIVER 1
#define CONFIG_FUSIV_BMDRIVER 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1845 */
#define cCONFIG_FUSIV_TIMERS 1
#define CONFIG_FUSIV_TIMERS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1506 */
#define cCONFIG_FUSIV_KERNEL_ETHERNET 1
#define CONFIG_FUSIV_KERNEL_ETHERNET 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1633 */
#define cCONFIG_FUSIV_KERNEL_ATM 1
#define CONFIG_FUSIV_KERNEL_ATM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1808 */
#define cCONFIG_FUSIV_KERNEL_UART2 1
#define CONFIG_FUSIV_KERNEL_UART2 1

#define cCONFIG_FUSIV_VX200 0

#define cCONFIG_FUSIV_VX160 0

#define cCONFIG_FUSIV_AT300 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3324 */
#define cCONFIG_FUSIV_REUSE_SKBS 1
#define CONFIG_FUSIV_REUSE_SKBS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1776 */
#define cCONFIG_FUSIV_KERNEL_PERI_AP 1
#define CONFIG_FUSIV_KERNEL_PERI_AP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1484 */
#define cNUM_PHYS 2
#define NUM_PHYS 2
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1632 */
#define cCONFIG_ARCH_AD6834_FAST3202 1
#define CONFIG_ARCH_AD6834_FAST3202 1

#define cCONFIG_SW_80211G_AR500XX 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:17 */
#define cCONFIG_SW_80211N_AR500XX 1
#define CONFIG_SW_80211N_AR500XX 1

#define cCONFIG_LIVEBOX1 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3227 */
#define cCONFIG_LIVEBOX 1
#define CONFIG_LIVEBOX 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1682 */
#define cCONFIG_LIVEBOX_SAGEM_SWITCH_FEATURE 1
#define CONFIG_LIVEBOX_SAGEM_SWITCH_FEATURE 1
#define CONFIG_LIVEBOX_SAGEM_SWITCH_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:109 */
#define cCONFIG_LIVEBOX_TV 1
#define CONFIG_LIVEBOX_TV 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:82 */
#define cCONFIG_LIVEBOX_MULTICAST_ROUTING 1
#define CONFIG_LIVEBOX_MULTICAST_ROUTING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:83 */
#define cCONFIG_LIVEBOX_MLTV_ROUTED 1
#define CONFIG_LIVEBOX_MLTV_ROUTED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:84 */
#define CONFIG_LIVEBOX_MLTV_FTTH_ROUTED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:76 */
#define CONFIG_LIVEBOX_MLTV_ADSL_ROUTED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:77 */
#define CONFIG_LIVEBOX_MLTV_BRIDGED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:78 */
#define CONFIG_LIVEBOX_MLTV_ADSL_BRIDGED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:80 */
#define cCONFIG_SAGEM_MULTI_STB 1
#define CONFIG_SAGEM_MULTI_STB 1

#define cCONFIG_SAGEM_FTTH_MULTI_STB 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:81 */
#define cCONFIG_SAGEM_ADSL_MULTI_STB 1
#define CONFIG_SAGEM_ADSL_MULTI_STB 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:85 */
#define cCONFIG_FTTH_ROUTED_DEFAULT 1
#define CONFIG_FTTH_ROUTED_DEFAULT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:79 */
#define cCONFIG_ADSL_ROUTED_DEFAULT 1
#define CONFIG_ADSL_ROUTED_DEFAULT 1

#define cCONFIG_LIVEBOX_VISIO 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:110 */
#define cCONFIG_LIVEBOX_LIVEZOOM 1
#define CONFIG_LIVEBOX_LIVEZOOM 1

#define cCONFIG_LIVEBOX_PHOTOBLOG 0

#define cCONFIG_LIVEBOX_TRACEABILITY 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3248 */
#define cCONFIG_LIVEBOX_VOIP 1
#define CONFIG_LIVEBOX_VOIP 1

#define cCONFIG_SAGEM_VOIP_PPP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:14 */
#define cCONFIG_SAGEM_VOIP_VCCONV 1
#define CONFIG_SAGEM_VOIP_VCCONV 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3308 */
#define cCONFIG_LIVEBOX_TELNET_LOGIN_FAILURE_DELAY 1
#define CONFIG_LIVEBOX_TELNET_LOGIN_FAILURE_DELAY 1

#define cCONFIG_LIVEBOX_SERIAL_LOGIN_FAILURE_DELAY 0

#define cCONFIG_LIVEBOX_PAIRING 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2884 */
#define CONFIG_LBV2_PAIRING 1

#define cCONFIG_LIVEBOX_MIGRATION 0

#define cCONFIG_LIVEBOX_LIB_MIGRATION 0

#define cCONFIG_LIVEBOX_MRA_WBM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3281 */
#define cCONFIG_RG_PERMST_ACCESS 1
#define CONFIG_RG_PERMST_ACCESS 1

#define cCONFIG_LIVEBOX_WIFIC_NTFY 0

#define cCONFIG_LIVEBOX_VER_MRA_FR 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:112 */
#define cCONFIG_LIVEBOX_VER_APP2_FR 1
#define CONFIG_LIVEBOX_VER_APP2_FR 1

#define cCONFIG_LIVEBOX_VER_MRA_OCH 0

#define cCONFIG_LIVEBOX_VER_APP2_OCH 0

#define cCONFIG_LIVEBOX_VER_APP2_OCH_V2 0

#define cCONFIG_LIVEBOX_VER_MRA_NL 0

#define cCONFIG_LIVEBOX_VER_APP2_NL 0

#define cCONFIG_LIVEBOX_VER_MRA_POL 0

#define cCONFIG_LIVEBOX_VER_APP2_POL 0

#define cCONFIG_LIVEBOX_VER_MRA_SP 0

#define cCONFIG_LIVEBOX_VER_APP2_SP 0

#define cCONFIG_LIVEBOX_VER_MRA_BE 0

#define cCONFIG_LIVEBOX_VER_APP2_BE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:49 */
#define cCONFIG_LIVEBOX_MEDIA_SERVER 1
#define CONFIG_LIVEBOX_MEDIA_SERVER 1

#define cCONFIG_LIVEBOX_MEDIA_SERVER_VIP 0

#define cCONFIG_LIVEBOX_TWONKY_WBM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3127 */
#define cCONFIG_LIVEBOX_ORANGE_TV_DHCP 1
#define CONFIG_LIVEBOX_ORANGE_TV_DHCP 1

#define cCONFIG_KS8695_FLASH_AM29LV033C_FEATURE 0

#define cCONFIG_KSFLASH_FEATURE 0

#define cCONFIG_CX8620X_COMMON 0

#define cCONFIG_CX8620X_FLASH_TE28F160C3_FEATURE 0

#define cCONFIG_CX8620X_FLASH_TE28F320C3_FEATURE 0

#define cCONFIG_CX8620X_FLASH_TE28F640C3_FEATURE 0

#define cCONFIG_CX8620X_SWITCH_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2857 */
#define cCONFIG_HOTPLUG 1
#define CONFIG_HOTPLUG 1

#define cCONFIG_MTD_BCM947XX_FEATURE 0

#define cCONFIG_MTD_XG1000_FEATURE 0

#define cCONFIG_IL_FEATURE 0

#define cCONFIG_IL_47XX_FEATURE 0

#define cCONFIG_WL_FEATURE 0

#define cCONFIG_HERMES_FEATURE 0

#define cCONFIG_PCMCIA_HERMES_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:81 */
#define CONFIG_RAMFS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:99 */
#define CONFIG_MODULES 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:88 */
#define cCONFIG_SYSFS 1
#define CONFIG_SYSFS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1119 */
#define CONFIG_MTD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2251 */
#define CONFIG_MTD_BLOCK 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2252 */
#define CONFIG_MTD_CFI 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2253 */
#define CONFIG_MTD_GEN_PROBE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2250 */
#define CONFIG_MTD_PARTITIONS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1124 */
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1125 */
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1126 */
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1127 */
#define CONFIG_MTD_CFI_I1 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1128 */
#define CONFIG_MTD_CFI_I2 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1120 */
#define CONFIG_MTD_CFI_AMDSTD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1129 */
#define CONFIG_MTD_CFI_UTIL 1

#define cCONFIG_NATSEMI_FEATURE 0

#define cCONFIG_NE2000_FEATURE 0

#define cCONFIG_NE2K_PCI_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:105 */
#define CONFIG_NET 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:106 */
#define CONFIG_NETDEVICES 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:113 */
#define CONFIG_NET_ETHERNET 1

#define cCONFIG_NETLINK_DEV_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:132 */
#define CONFIG_NET_RADIO 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:133 */
#define cCONFIG_NET_WIRELESS 1
#define CONFIG_NET_WIRELESS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:284 */
#define CONFIG_OPENRG 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:107 */
#define CONFIG_PACKET 1

#define cCONFIG_PCF8594C2_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1155 */
#define CONFIG_PCI 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1156 */
#define CONFIG_PCI_AUTO 1

#define cCONFIG_PCMCIA_DEVELOPMENT 0

#define cCONFIG_PCNET32_FEATURE 0

#define cCONFIG_RG_PPTPS 0

#define cCONFIG_PPC 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:384 */
#define cCONFIG_RG_PPP 1
#define cCONFIG_RG_PPP_FEATURE 1
#define CONFIG_RG_PPP_FEATURE 1
#define CONFIG_RG_PPP_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:390 */
#define cCONFIG_RG_PPP_BSDCOMP 1
#define CONFIG_RG_PPP_BSDCOMP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:389 */
#define cCONFIG_RG_PPP_DEFLATE 1
#define CONFIG_RG_PPP_DEFLATE 1

#define cCONFIG_RG_PPP_ON_DEMAND_AS_DEFAULT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:396 */
#define cCONFIG_RG_PPP_ON_DEMAND_DEFAULT_MAX_IDLE_TIME 1200
#define CONFIG_RG_PPP_ON_DEMAND_DEFAULT_MAX_IDLE_TIME 1200
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:405 */
#define cCONFIG_RG_PPP_DEFAULT_BSD_COMPRESSION 1
#define CONFIG_RG_PPP_DEFAULT_BSD_COMPRESSION 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:414 */
#define cCONFIG_RG_PPP_DEFAULT_DEFLATE_COMPRESSION 1
#define CONFIG_RG_PPP_DEFAULT_DEFLATE_COMPRESSION 1

#define cCONFIG_RG_PPP_MPPE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:432 */
#define cCONFIG_RG_PPPOA_FEATURE 1
#define CONFIG_RG_PPPOA_FEATURE 1
#define CONFIG_RG_PPPOA_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:385 */
#define cCONFIG_RG_PPPOE 1
#define CONFIG_RG_PPPOE 1

#define cCONFIG_RG_PPPOES 0

#define cCONFIG_RG_PPPOS_CLI 0

#define cCONFIG_RG_HSS 0

#define cCONFIG_RG_IPV6 0

#define cCONFIG_RG_PPTP 0

#define cCONFIG_RG_PPTPC 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3219 */
#define cCONFIG_RG_L2TPC 1
#define CONFIG_RG_L2TPC 1

#define cCONFIG_PRISM2_PCI_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:84 */
#define CONFIG_PROC_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1232 */
#define CONFIG_IKCONFIG 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1233 */
#define CONFIG_IKCONFIG_PROC 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:229 */
#define CONFIG_RG_ALG 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:238 */
#define CONFIG_RG_ALG_ICMP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:239 */
#define cCONFIG_RG_ALG_PORT_TRIGGER 1
#define CONFIG_RG_ALG_PORT_TRIGGER 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:240 */
#define cCONFIG_RG_ALG_FTP 1
#define CONFIG_RG_ALG_FTP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:241 */
#define cCONFIG_RG_ALG_RTSP 1
#define CONFIG_RG_ALG_RTSP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:232 */
#define cCONFIG_RG_ALG_H323 1
#define CONFIG_RG_ALG_H323 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2392 */
#define cCONFIG_RG_ALG_SIP 1
#define CONFIG_RG_ALG_SIP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:231 */
#define cCONFIG_RG_ALG_MGCP 1
#define CONFIG_RG_ALG_MGCP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:235 */
#define cCONFIG_RG_ALG_PPTP 1
#define CONFIG_RG_ALG_PPTP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:234 */
#define cCONFIG_RG_ALG_MSNMS 1
#define CONFIG_RG_ALG_MSNMS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:236 */
#define cCONFIG_RG_ALG_IPSEC 1
#define CONFIG_RG_ALG_IPSEC 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:237 */
#define cCONFIG_RG_ALG_L2TP 1
#define CONFIG_RG_ALG_L2TP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:233 */
#define cCONFIG_RG_ALG_AIM 1
#define CONFIG_RG_ALG_AIM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:277 */
#define cCONFIG_RG_ALG_DNS 1
#define CONFIG_RG_ALG_DNS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:278 */
#define cCONFIG_RG_ALG_DHCP 1
#define CONFIG_RG_ALG_DHCP 1

#define cCONFIG_RG_ALG_USERSPACE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:242 */
#define cCONFIG_SAGEM_ALG_SNMP 1
#define CONFIG_SAGEM_ALG_SNMP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3284 */
#define cCONFIG_RG_ADI_FASTPATH_BRIDGE 1
#define cCONFIG_RG_ADI_FASTPATH_BRIDGE_FEATURE 1
#define CONFIG_RG_ADI_FASTPATH_BRIDGE_FEATURE 1
#define CONFIG_RG_ADI_FASTPATH_BRIDGE_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:223 */
#define cCONFIG_RG_BRIDGE 1
#define cCONFIG_RG_BRIDGE_FEATURE 1
#define CONFIG_RG_BRIDGE_FEATURE 1
#define CONFIG_RG_BRIDGE_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:442 */
#define cCONFIG_RG_VLAN_BRIDGE 1
#define CONFIG_RG_VLAN_BRIDGE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:444 */
#define cCONFIG_RG_8021Q_IF 1
#define CONFIG_RG_8021Q_IF 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3287 */
#define cCONFIG_RG_FASTPATH 1
#define cCONFIG_RG_FASTPATH_FEATURE 1
#define CONFIG_RG_FASTPATH_FEATURE 1
#define CONFIG_RG_FASTPATH_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3289 */
#define CONFIG_RG_FASTPATH_PLAT_PATH vendor/adi/ad6843/rg_modules
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3290 */
#define cCONFIG_RG_FASTPATH_PLAT_AD6834 1
#define CONFIG_RG_FASTPATH_PLAT_AD6834 1

#define cCONFIG_RG_CABLEHOME 0

#define cCONFIG_RG_CABLEHOME_10 0

#define cCONFIG_RG_CABLEHOME_11 0

#define cCONFIG_RG_CABLEHOME_EMBEDDED 0

#define cCONFIG_RG_CABLEHOME_FULL_WBM 0

#define cCONFIG_RG_DSL_CH 0

#define cCONFIG_RG_CH_FW 0

#define cCONFIG_RG_CH_EVT_RPT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:331 */
#define CONFIG_RG_CHRDEV 1

#define cCONFIG_RG_CHWAN_FEATURE 0

#define cCONFIG_RG_USFS_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3210 */
#define cCONFIG_RG_PPPOE_RELAY 1
#define cCONFIG_RG_PPPOE_RELAY_FEATURE 1
#define CONFIG_RG_PPPOE_RELAY_FEATURE 1
#define CONFIG_RG_PPPOE_RELAY_MODULE 1

#define cCONFIG_RG_BROUTE_FEATURE 0

#define cCONFIG_RG_ELVIS 0

#define cCONFIG_RG_DSLHOME 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:174 */
#define cCONFIG_RG_FIREWALL 1
#define CONFIG_RG_FIREWALL 1

#define cCONFIG_RG_FW_ICSA 0

#define cCONFIG_RG_GDBSERVER 0

#define cCONFIG_RG_ADV_SERVICES 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1145 */
#define CONFIG_RG_IGD 1

#define cCONFIG_RG_IGD_XBOX 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:116 */
#define cCONFIG_RG_IGMP_PROXY 1
#define cCONFIG_RG_IGMP_PROXY_FEATURE 1
#define CONFIG_RG_IGMP_PROXY_FEATURE 1
#define CONFIG_RG_IGMP_PROXY_MODULE 1

#define cCONFIG_RG_MCAST_RELAY 0
#define cCONFIG_RG_MCAST_RELAY_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2413 */
#define cCONFIG_RG_JFW_FEATURE 1
#define CONFIG_RG_JFW_FEATURE 1
#define CONFIG_RG_JFW_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:248 */
#define cCONFIG_RG_MSS 1
#define cCONFIG_RG_MSS_FEATURE 1
#define CONFIG_RG_MSS_FEATURE 1
#define CONFIG_RG_MSS_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:245 */
#define cCONFIG_RG_FUWR 1
#define cCONFIG_RG_FUWR_FEATURE 1
#define CONFIG_RG_FUWR_FEATURE 1
#define CONFIG_RG_FUWR_MODULE 1

#define cCONFIG_RG_LAN_UPGRADE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:65 */
#define CONFIG_RG_OS_LINUX 1

#define cCONFIG_RG_OS_VXWORKS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:226 */
#define cCONFIG_RG_NAT 1
#define CONFIG_RG_NAT 1

#define cCONFIG_RG_NETKIT 0

#define cCONFIG_RG_NETTOOLS_ARP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2356 */
#define CONFIG_RG_OPENSSL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2359 */
#define cCONFIG_RG_CRYPTO 1
#define CONFIG_RG_CRYPTO 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:361 */
#define cCONFIG_RG_SSL 1
#define CONFIG_RG_SSL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2951 */
#define cCONFIG_RG_PERM_STORAGE 1
#define CONFIG_RG_PERM_STORAGE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3241 */
#define cCONFIG_RG_PERM_STORAGE_VENDOR_HEADER 1
#define CONFIG_RG_PERM_STORAGE_VENDOR_HEADER 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:294 */
#define cCONFIG_RG_KOS 1
#define cCONFIG_RG_KOS_FEATURE 1
#define CONFIG_RG_KOS_FEATURE 1
#define CONFIG_RG_KOS_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:418 */
#define cCONFIG_RG_KOS_KNET 1
#define CONFIG_RG_KOS_KNET 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:89 */
#define cCONFIG_RG_IPV4_FEATURE 1
#define CONFIG_RG_IPV4_FEATURE 1
#define CONFIG_RG_IPV4_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:161 */
#define cCONFIG_RG_RIP 1
#define CONFIG_RG_RIP 1

#define cCONFIG_RG_RMT_UPDATE 0

#define cCONFIG_RG_RMT_UPGRADE_IMG_IN_MEM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:173 */
#define cCONFIG_RG_RNAT 1
#define CONFIG_RG_RNAT 1

#define cCONFIG_BIDIR_NAT 0

#define cCONFIG_RG_RNDIS_FEATURE 0

#define cCONFIG_RG_STANDALONE_PS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:326 */
#define CONFIG_RG_SYSINIT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2769 */
#define cCONFIG_RG_SYSLOG_REMOTE 1
#define CONFIG_RG_SYSLOG_REMOTE 1

#define cCONFIG_RG_TFTP_SERVER 0

#define cCONFIG_RG_TFTP_SERVER_PASSWORD 0

#define cCONFIG_RG_TFTP_UPGRADE 0

#define cCONFIG_RG_UCD_SNMP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1144 */
#define cCONFIG_RG_UPNP 1
#define CONFIG_RG_UPNP 1

#define cCONFIG_RG_USB_SLAVE 0
#define cCONFIG_RG_USB_SLAVE_FEATURE 0

#define cCONFIG_RG_WAN_UPGRADE 0

#define cCONFIG_RG_WLAN_AUTO_CHANNEL_SELECT 0

#define cCONFIG_RG_RMT_UPD_LOW_MEM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:305 */
#define cCONFIG_RG_DNS 1
#define CONFIG_RG_DNS 1

#define cCONFIG_RG_DNS_CONCURRENT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:163 */
#define cCONFIG_DNS_OVERRIDE 1
#define CONFIG_DNS_OVERRIDE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:169 */
#define cCONFIG_RG_DNS_ROUTE 1
#define CONFIG_RG_DNS_ROUTE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:165 */
#define cCONFIG_RG_DNS_DOMAIN_ROUTING 1
#define CONFIG_RG_DNS_DOMAIN_ROUTING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:312 */
#define cCONFIG_RG_DDNS 1
#define CONFIG_RG_DDNS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:364 */
#define cCONFIG_RG_ENTFY 1
#define CONFIG_RG_ENTFY 1

#define cCONFIG_RG_HTTP_PROXY 0

#define cCONFIG_RG_MAIL_FILTER 0

#define cCONFIG_RG_URL_KEYWORD_FILTER 0

#define cCONFIG_RG_SURFCONTROL 0

#define cCONFIG_RG_8021X 0

#define cCONFIG_RG_8021X_MD5 0

#define cCONFIG_RG_8021X_TTLS 0

#define cCONFIG_RG_8021X_PKTFIL_FEATURE 0

#define cCONFIG_RG_8021X_TLS 0

#define cCONFIG_RG_8021X_RADIUS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:139 */
#define cCONFIG_RG_8021X_WBM 1
#define CONFIG_RG_8021X_WBM 1

#define cCONFIG_RG_RADIUS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:136 */
#define CONFIG_RG_VENDOR_WLAN_SEC 1

#define cCONFIG_RG_RADIUS_WBM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2998 */
#define cCONFIG_RG_AUTH 1
#define CONFIG_RG_AUTH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:193 */
#define CONFIG_RG_SSID_NAME "openrg"

#define cCONFIG_RG_RADIUS_IN_CONN 0

#define cCONFIG_RG_RADIUS_LOGIN_AUTH 0

#define cCONFIG_RG_WPA 0

#define cCONFIG_RG_WPA_BCM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:138 */
#define cCONFIG_SAGEM_WPA 1
#define CONFIG_SAGEM_WPA 1

#define cCONFIG_SAGEM_WPA_RALINK 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:137 */
#define cCONFIG_RG_WPA_WBM 1
#define CONFIG_RG_WPA_WBM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:213 */
#define cCONFIG_RG_DHCPS 1
#define CONFIG_RG_DHCPS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:315 */
#define cCONFIG_RG_DHCPC 1
#define CONFIG_RG_DHCPC 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:217 */
#define cCONFIG_RG_DHCPR 1
#define CONFIG_RG_DHCPR 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2320 */
#define cCONFIG_RG_DHCP_PKTFIL_FEATURE 1
#define CONFIG_RG_DHCP_PKTFIL_FEATURE 1
#define CONFIG_RG_DHCP_PKTFIL_MODULE 1

#define cCONFIG_RG_PKTCBL_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1409 */
#define cCONFIG_RG_SSI 1
#define CONFIG_RG_SSI 1

#define cCONFIG_RG_SSI_PAGES 0

#define cCONFIG_RG_WBM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:105 */
#define cCONFIG_RG_GUI 1
#define CONFIG_RG_GUI 1

#define cCONFIG_RG_TCPDUMP 0

#define cCONFIG_FREESWAN_COMMON 0

#define cCONFIG_RG_ACL 0

#define cCONFIG_RG_ATTR 0

#define cCONFIG_RG_BACKUP 0

#define cCONFIG_RG_BOOTLDR 0

#define cCONFIG_RG_CABLEHOME_COMMON 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3022 */
#define cCONFIG_RG_DHCP_COMMON 1
#define CONFIG_RG_DHCP_COMMON 1

#define cCONFIG_RG_SAMPLES_COMMON 0

#define cCONFIG_RG_DOSFSTOOLS  0

#define cCONFIG_RG_E2FSPROGS 0

#define cCONFIG_RG_FLEX 0

#define cCONFIG_RG_LIBPCAP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3012 */
#define cCONFIG_RG_LZMA 1
#define CONFIG_RG_LZMA 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3005 */
#define cCONFIG_RG_MGT 1
#define CONFIG_RG_MGT 1

#define cCONFIG_RG_OPENSSL_COMMON 0

#define cCONFIG_RG_READLINE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3027 */
#define cCONFIG_RG_RGLOADER_COMMON 1
#define CONFIG_RG_RGLOADER_COMMON 1

#define cCONFIG_RG_STAR 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3053 */
#define cCONFIG_RG_SYSLOG_COMMON 1
#define CONFIG_RG_SYSLOG_COMMON 1

#define cCONFIG_RG_TERMCAP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3040 */
#define cCONFIG_RG_TEST_TOOLS 1
#define CONFIG_RG_TEST_TOOLS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3004 */
#define cCONFIG_RG_TZ 1
#define CONFIG_RG_TZ 1

#define cCONFIG_RG_USAGI 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3035 */
#define cCONFIG_RG_UTIL_LINUX 1
#define CONFIG_RG_UTIL_LINUX 1

#define cCONFIG_GUI_RG 0

#define cCONFIG_GUI_BELKIN 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3237 */
#define cCONFIG_GUI_LIVEBOX1 1
#define CONFIG_GUI_LIVEBOX1 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2383 */
#define cCONFIG_RG_LIBIMAGE 1
#define CONFIG_RG_LIBIMAGE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2376 */
#define cCONFIG_RG_LIBIMAGE_DIM 1
#define CONFIG_RG_LIBIMAGE_DIM 1

#define cCONFIG_RG_LIBJPEG 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2414 */
#define cCONFIG_RG_NETOBJ 1
#define CONFIG_RG_NETOBJ 1

#define cCONFIG_RG_LAN_BRIDGE_CONST 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2402 */
#define cCONFIG_RG_AUTO_DST 1
#define CONFIG_RG_AUTO_DST 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:372 */
#define CONFIG_RG_TZ_COMMON 1

#define cCONFIG_RG_TZ_FULL 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2404 */
#define CONFIG_RG_TZ_YEARS 5
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2386 */
#define cCONFIG_RG_HTTPS 1
#define CONFIG_RG_HTTPS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2389 */
#define cCONFIG_HTTP_CGI_PROCESS 1
#define CONFIG_HTTP_CGI_PROCESS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:220 */
#define cCONFIG_RG_TELNETS 1
#define CONFIG_RG_TELNETS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2760 */
#define cCONFIG_RG_SYSLOG 1
#define CONFIG_RG_SYSLOG 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2761 */
#define cCONFIG_RG_LOG_DEV_FEATURE 1
#define CONFIG_RG_LOG_DEV_FEATURE 1
#define CONFIG_RG_LOG_DEV_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2766 */
#define CONFIG_RG_KERN_LOG 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2689 */
#define CONFIG_RG_LOG_DEV_BUF_SIZE 16384
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2690 */
#define CONFIG_RG_SYSLOG_FW_DEF_SIZE 16384
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2949 */
#define cCONFIG_RG_CLI 1
#define CONFIG_RG_CLI 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2956 */
#define CONFIG_RG_CLI_SERIAL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:144 */
#define CONFIG_RG_TTYP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:300 */
#define CONFIG_RG_LOGIN 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:257 */
#define cCONFIG_RG_STATIC_ROUTE 1
#define CONFIG_RG_STATIC_ROUTE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:337 */
#define cCONFIG_RG_BUSYBOX 1
#define CONFIG_RG_BUSYBOX 1

#define cCONFIG_RG_NO_BUSYBOX 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:306 */
#define CONFIG_RG_ERESOLV 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2958 */
#define cCONFIG_RG_WGET 1
#define CONFIG_RG_WGET 1

#define cCONFIG_RG_NON_ROUTABLE_LAN_DEVICE_IP 0

#define cCONFIG_RG_FREESWAN 0

#define cCONFIG_RG_X509 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2347 */
#define cCONFIG_RG_CERT 1
#define CONFIG_RG_CERT 1

#define cCONFIG_RG_KERBEROS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2948 */
#define CONFIG_RGLOADER_CLI 1

#define cCONFIG_RTL8139_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1178 */
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1497 */
#define cCONFIG_SDRAM_SIZE 32
#define CONFIG_SDRAM_SIZE 32
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1499 */
#define CONFIG_FLASH_SIZE 8
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1109 */
#define CONFIG_SERIAL_CORE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1110 */
#define CONFIG_SERIAL_CORE_CONSOLE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1106 */
#define CONFIG_SERIAL_8250 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1107 */
#define CONFIG_SERIAL_8250_CONSOLE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1108 */
#define CONFIG_SERIAL_8250_NR_UARTS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3085 */
#define CONFIG_SYN_COOKIES 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:79 */
#define CONFIG_SYSCTL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2767 */
#define CONFIG_SYSLOG_UNIXSOCK_SUPPORT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:142 */
#define CONFIG_SYSVIPC 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2952 */
#define CONFIG_TEST_TOOLS_PING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:265 */
#define CONFIG_TEST_TOOLS_CONN_SPEED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:309 */
#define cCONFIG_RG_TODC 1
#define CONFIG_RG_TODC 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_host.c:388 */
#define cCONFIG_ULIBC 1
#define CONFIG_ULIBC 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3074 */
#define CONFIG_UNIX 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1137 */
#define cCONFIG_USB_FEATURE 1
#define CONFIG_USB_FEATURE 1
#define CONFIG_USB 1

#define cCONFIG_RG_USB_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:41 */
#define CONFIG_WPS_SUPPORT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:43 */
#define CONFIG_SUPERVISOR_SAGEM_EZP_WPS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:44 */
#define CONFIG_SAGEM_TR_MONITORING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1142 */
#define cCONFIG_USB_STORAGE_FEATURE 1
#define CONFIG_USB_STORAGE_FEATURE 1
#define CONFIG_USB_STORAGE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:65 */
#define CONFIG_USB_DEVICEFS 1

#define cCONFIG_USB_OHCI_FEATURE 0

#define cCONFIG_USB_UHCI_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1141 */
#define cCONFIG_USB_EHCI_HCD_FEATURE 1
#define CONFIG_USB_EHCI_HCD_FEATURE 1
#define CONFIG_USB_EHCI_HCD_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1140 */
#define cCONFIG_USB_OHCI_HCD_FEATURE 1
#define CONFIG_USB_OHCI_HCD_FEATURE 1
#define CONFIG_USB_OHCI_HCD_MODULE 1

#define cCONFIG_USB_RNDIS_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1138 */
#define CONFIG_USB_ARCH_HAS_HCD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1139 */
#define CONFIG_USB_ARCH_HAS_OHCI 1

#define cCONFIG_USB_GADGET_FEATURE 0

#define cCONFIG_USB_ETH_FEATURE 0

#define cCONFIG_USB_VOX160_FEATURE 0

#define cCONFIG_VALGRIND 0

#define cCONFIG_ZOOM_CM_FEATURE 0

#define cCONFIG_PCBOX 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1172 */
#define TARGET_ENDIANESS BIG
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1685 */
#define BOARD F@ST 3202
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1686 */
#define FIRM Sagem

#define cCONFIG_RG_TELEPHONY 0

#define cCONFIG_RG_VOATM 0

#define cCONFIG_RG_VOATM_ELCP_FEATURE 0

#define cCONFIG_RG_VOATM_CAS_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3083 */
#define cCONFIG_RG_FACTORY_SETTINGS 1
#define CONFIG_RG_FACTORY_SETTINGS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2918 */
#define cCONFIG_RG_HW_BUTTONS_FEATURE 1
#define CONFIG_RG_HW_BUTTONS_FEATURE 1
#define CONFIG_RG_HW_BUTTONS_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:650 */
#define CONFIG_RG_CONSOLE_DEVICE ttyS0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3198 */
#define CONFIG_FORCE_RECOVERY 1

#define cCONFIG_SAMBA 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:52 */
#define cCONFIG_SAGEM_SAMBA 1
#define CONFIG_SAGEM_SAMBA 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:87 */
#define cCONFIG_SAGEM_IPP_PRINT 1
#define CONFIG_SAGEM_IPP_PRINT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:11 */
#define CONFIG_ETH_SWITCH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2894 */
#define CONFIG_WAN_LED_BLINKING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2900 */
#define CONFIG_SHUTDOWN_BOX 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2893 */
#define CONFIG_REBOOT_BUTTON 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3089 */
#define OPENRG_CHRDEV_MAJOR 240
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:3088 */
#define OPENRG_CHRDEV_NAME "rg_chrdev"

#define cCONFIG_ATHEROS_AR531X_MIPS 0

#define cCONFIG_ARCH_WRT108G 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1778 */
#define cCONFIG_RG_ATHEROS 1
#define cCONFIG_RG_ATHEROS_FEATURE 1
#define CONFIG_RG_ATHEROS_FEATURE 1
#define CONFIG_RG_ATHEROS_MODULE 1

#define cCONFIG_RG_ATHEROS_HW_AR5212 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_hw_config.c:5 */
#define cCONFIG_RG_ATHEROS_HW_AR5416 1
#define CONFIG_RG_ATHEROS_HW_AR5416 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:159 */
#define cCONFIG_RG_DEV_IF_WIFI 1
#define CONFIG_RG_DEV_IF_WIFI 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:162 */
#define CONFIG_RG_DEV_IF_AR5416_VAP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:169 */
#define CONFIG_RG_DEV_IF_AR5416_VAP_SLAVE 1

#define cCONFIG_RG_DEV_IF_RT2880 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:141 */
#define cCONFIG_RG_HOSTAPD 1
#define CONFIG_RG_HOSTAPD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:143 */
#define cCONFIG_HOSTAPD_RSN_PREAUTH 1
#define CONFIG_HOSTAPD_RSN_PREAUTH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:142 */
#define cCONFIG_HOSTAPD_DRIVER_MADWIFI 1
#define CONFIG_HOSTAPD_DRIVER_MADWIFI 1

#define cCONFIG_TI_404_MIPS 0

#define cCONFIG_TI_404_COMMON 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2315 */
#define CONFIG_GCC_CAN_INLINE 1

#define cCONFIG_I386 0

#define cCONFIG_UM 0

#define cCONFIG_RG_FILESERVER 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2813 */
#define CONFIG_RG_STORAGE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2873 */
#define CONFIG_RG_STORAGE_UTILS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2540 */
#define CONFIG_RG_LARGE_FILE_SUPPORT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2870 */
#define CONFIG_RG_CODEPAGE "437"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2863 */
#define CONFIG_MSDOS_PARTITION 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2861 */
#define CONFIG_FAT_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2866 */
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2862 */
#define CONFIG_MSDOS_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2864 */
#define CONFIG_VFAT_FS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2906 */
#define CONFIG_NLS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2867 */
#define cCONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2911 */
#define CONFIG_NLS_DEFAULT "437"
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2907 */
#define CONFIG_NLS_CODEPAGE_437 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2908 */
#define CONFIG_NLS_CODEPAGE_850 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2909 */
#define CONFIG_NLS_ISO8859_1 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2910 */
#define CONFIG_NLS_UTF8 1

#define cCONFIG_RG_FILESERVER_ACLS 0

#define cCONFIG_RG_FILESERVER_ACLS_DEBUG 0

#define cCONFIG_RG_RAID 0

#define cCONFIG_RG_RAID_IDE_ONLY 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2810 */
#define CONFIG_SCSI 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2811 */
#define CONFIG_BLK_DEV_SD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2812 */
#define CONFIG_SD_EXTRA_DEVS 32

#define cCONFIG_FLASH 0
#define cCONFIG_FLASH_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2449 */
#define CONFIG_VLAN_8021Q 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2446 */
#define cCONFIG_RG_VLAN_8021Q 1
#define CONFIG_RG_VLAN_8021Q 1

#define cCONFIG_RG_VLAN_DEBUG_TOOLS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:70 */
#define CONFIG_VLAN_8021Q_FAST 1

#define cCONFIG_AT93CXX_FEATURE 0

#define cCONFIG_ADM6996_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:45 */
#define cCONFIG_RG_OS_LINUX_26 1
#define CONFIG_RG_OS_LINUX_26 1

#define cCONFIG_RG_OS_LINUX_24 0

#define cCONFIG_RG_OS_LINUX_22 0

#define cCONFIG_RG_EMI 0

#define cCONFIG_RG_EMI_IRDA 0

#define cCONFIG_RG_EMI_USB_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2968 */
#define CONFIG_RG_DIST_LANG eng
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1190 */
#define CONFIG_32BIT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1197 */
#define CONFIG_FLATMEM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1198 */
#define CONFIG_FLAT_NODE_MEM_MAP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1196 */
#define CONFIG_SPLIT_PTLOCK_CPUS 4

#define cCONFIG_RG_UML 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2564 */
#define CONFIG_ZLIB_INFLATE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2397 */
#define CONFIG_ZLIB_DEFLATE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:117 */
#define cCONFIG_USB_SERIAL_FEATURE 1
#define CONFIG_USB_SERIAL_FEATURE 1
#define CONFIG_USB_SERIAL_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:118 */
#define cCONFIG_USB_SERIAL_CP2101_FEATURE 1
#define CONFIG_USB_SERIAL_CP2101_FEATURE 1
#define CONFIG_USB_SERIAL_CP2101_MODULE 1

#define cCONFIG_USB_SERIAL_OPTION_FEATURE 0

#define cCONFIG_PPP_FEATURE 0

#define cCONFIG_PPP_ASYNC_FEATURE 0

#define cCONFIG_PPP_SYNC_TTY_FEATURE 0

#define cCONFIG_CRC_CCITT_FEATURE 0

#define cCONFIG_RG_PROXY_ARP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:430 */
#define cCONFIG_RG_OAM_PING 1
#define CONFIG_RG_OAM_PING 1

#define cCONFIG_STOP_ON_INIT_FAIL 0

#define cCONFIG_RG_KCALL_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2981 */
#define cCONFIG_RG_FRAG_CACHE_FEATURE 1
#define CONFIG_RG_FRAG_CACHE_FEATURE 1
#define CONFIG_RG_FRAG_CACHE_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2364 */
#define cCONFIG_RG_XML 1
#define CONFIG_RG_XML 1

#define cCONFIG_WBM_PAGES_EXPIRE 0

#define cCONFIG_RG_AUTOTEST 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1431 */
#define CONFIG_RG_FW_NAT_STATE_TABLE_SIZE 3000

#define cCONFIG_RG_TUTORIAL 0

#define cCONFIG_RG_TUTORIAL_ADVANCED 0

#define cCONFIG_RG_WEBCAM 0

#define cCONFIG_ZC_IP_AUTO_DETECTION 0

#define cCONFIG_ZC_AUTO_CONFIG_NON_PNP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1143 */
#define CONFIG_USB_PRINTER 1

#define cCONFIG_RG_PRINT_SERVER 0

#define cCONFIG_RG_SAMBA_PRINTING 0

#define cCONFIG_RG_IPP 0

#define cCONFIG_RG_LPD 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:287 */
#define cCONFIG_RG_LANG 1
#define CONFIG_RG_LANG 1

#define cCONFIG_RG_DYN_FLASH_LAYOUT 0

#define cCONFIG_RG_DNS_USE_ISP_DOMAIN 0

#define cCONFIG_RG_VOIP 0

#define cCONFIG_RG_IPPHONE 0

#define cCONFIG_RG_ATA 0

#define cCONFIG_RG_VOIP_SIP 0

#define cCONFIG_RG_VOIP_H323 0

#define cCONFIG_RG_VOIP_MGCP 0

#define cCONFIG_RG_VOIP_NUMBER_OF_LINES 0

#define cCONFIG_RG_VOIP_HW_EMULATION 0

#define cCONFIG_RG_VOIP_USE_SIP_ALG 0

#define cCONFIG_RG_VOIP_RV 0

#define cCONFIG_RG_VOIP_RV_SIP 0

#define cCONFIG_RG_VOIP_RV_H323 0

#define cCONFIG_RG_VOIP_RV_MGCP 0

#define cCONFIG_RG_VOIP_OSIP 0

#define cCONFIG_RG_VOIP_ASTERISK 0

#define cCONFIG_RG_RTP 0
#define cCONFIG_RG_RTP_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_host.c:1163 */
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:252 */
#define cCONFIG_RG_OSS_RMT 1
#define CONFIG_RG_OSS_RMT 1

#define cCONFIG_HITRON_BSP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:251 */
#define cCONFIG_RG_RMT_MNG 1
#define CONFIG_RG_RMT_MNG 1

#define cCONFIG_SL2312_COMMON 0

#define cCONFIG_SL2312_FLASH_FEATURE 0

#define cCONFIG_USB_OHCI_SL2312_FEATURE 0

#define cCONFIG_SL2312_ETH_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:419 */
#define CONFIG_RG_EVENT_LOGGING 1

#define cCONFIG_RG_WINS_SERVER 0

#define cCONFIG_RG_FTP_SERVER 0

#define cCONFIG_RG_MAIL_SERVER 0

#define cCONFIG_RG_WEB_SERVER 0

#define cCONFIG_RG_FS_BACKUP 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:573 */
#define cCONFIG_TOS_DSCP_RFC2474_FEATURE 1
#define CONFIG_TOS_DSCP_RFC2474_FEATURE 1
#define CONFIG_TOS_DSCP_RFC2474 1

#define cCONFIG_RG_IPROUTE2 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3257 */
#define cCONFIG_RG_IPROUTE2_SAGEM 1
#define CONFIG_RG_IPROUTE2_SAGEM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3243 */
#define cCONFIG_RG_QOS 1
#define CONFIG_RG_QOS 1

#define cCONFIG_RG_QOS_MGT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:626 */
#define cCONFIG_RG_QOS_INGRESS_FEATURE 1
#define CONFIG_RG_QOS_INGRESS_FEATURE 1
#define CONFIG_RG_QOS_INGRESS_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:577 */
#define cCONFIG_NET_SCHED_FEATURE 1
#define CONFIG_NET_SCHED_FEATURE 1
#define CONFIG_NET_SCHED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:584 */
#define cCONFIG_NET_SCH_INGRESS_FEATURE 1
#define CONFIG_NET_SCH_INGRESS_FEATURE 1
#define CONFIG_NET_SCH_INGRESS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:580 */
#define cCONFIG_NET_SCH_HTB_FEATURE 1
#define CONFIG_NET_SCH_HTB_FEATURE 1
#define CONFIG_NET_SCH_HTB 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:582 */
#define cCONFIG_NET_SCH_TBF_FEATURE 1
#define CONFIG_NET_SCH_TBF_FEATURE 1
#define CONFIG_NET_SCH_TBF 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:620 */
#define cCONFIG_NET_SCH_ATM_FEATURE 1
#define CONFIG_NET_SCH_ATM_FEATURE 1
#define CONFIG_NET_SCH_ATM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:586 */
#define cCONFIG_NET_SCH_PRIO_FEATURE 1
#define CONFIG_NET_SCH_PRIO_FEATURE 1
#define CONFIG_NET_SCH_PRIO 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:588 */
#define cCONFIG_NET_SCH_RED_FEATURE 1
#define CONFIG_NET_SCH_RED_FEATURE 1
#define CONFIG_NET_SCH_RED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:590 */
#define cCONFIG_NET_SCH_SFQ_FEATURE 1
#define CONFIG_NET_SCH_SFQ_FEATURE 1
#define CONFIG_NET_SCH_SFQ 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:592 */
#define cCONFIG_NET_SCH_DSMARK_FEATURE 1
#define CONFIG_NET_SCH_DSMARK_FEATURE 1
#define CONFIG_NET_SCH_DSMARK 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:594 */
#define cCONFIG_NET_QOS_FEATURE 1
#define CONFIG_NET_QOS_FEATURE 1
#define CONFIG_NET_QOS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:596 */
#define cCONFIG_NET_ESTIMATOR_FEATURE 1
#define CONFIG_NET_ESTIMATOR_FEATURE 1
#define CONFIG_NET_ESTIMATOR 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:598 */
#define cCONFIG_NET_CLS_FEATURE 1
#define CONFIG_NET_CLS_FEATURE 1
#define CONFIG_NET_CLS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:600 */
#define cCONFIG_NET_CLS_POLICE_FEATURE 1
#define CONFIG_NET_CLS_POLICE_FEATURE 1
#define CONFIG_NET_CLS_POLICE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:602 */
#define cCONFIG_NET_CLS_TCINDEX_FEATURE 1
#define CONFIG_NET_CLS_TCINDEX_FEATURE 1
#define CONFIG_NET_CLS_TCINDEX 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:604 */
#define cCONFIG_NET_CLS_FW_FEATURE 1
#define CONFIG_NET_CLS_FW_FEATURE 1
#define CONFIG_NET_CLS_FW 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:606 */
#define cCONFIG_NET_CLS_U32_FEATURE 1
#define CONFIG_NET_CLS_U32_FEATURE 1
#define CONFIG_NET_CLS_U32 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:608 */
#define cCONFIG_NET_CLS_RSVP_FEATURE 1
#define CONFIG_NET_CLS_RSVP_FEATURE 1
#define CONFIG_NET_CLS_RSVP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:610 */
#define cCONFIG_NET_CLS_RSVP6_FEATURE 1
#define CONFIG_NET_CLS_RSVP6_FEATURE 1
#define CONFIG_NET_CLS_RSVP6 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:614 */
#define cCONFIG_IP_ROUTE_MULTIPATH_FEATURE 1
#define CONFIG_IP_ROUTE_MULTIPATH_FEATURE 1
#define CONFIG_IP_ROUTE_MULTIPATH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:616 */
#define cCONFIG_IP_ROUTE_VERBOSE_FEATURE 1
#define CONFIG_IP_ROUTE_VERBOSE_FEATURE 1
#define CONFIG_IP_ROUTE_VERBOSE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:623 */
#define cCONFIG_IP_ROUTE_FWMARK_FEATURE 1
#define CONFIG_IP_ROUTE_FWMARK_FEATURE 1
#define CONFIG_IP_ROUTE_FWMARK 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:208 */
#define CONFIG_RG_FOUNDATION_CORE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:181 */
#define CONFIG_RG_TARGET_LINUX 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_host.c:64 */
#define CONFIG_RG_HOST_LINUX 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3201 */
#define MODULE_RG_FOUNDATION 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3204 */
#define MODULE_RG_ADVANCED_MANAGEMENT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3209 */
#define MODULE_RG_SNMP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3205 */
#define MODULE_RG_DSL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3206 */
#define MODULE_RG_PPP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3203 */
#define MODULE_RG_VLAN 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3208 */
#define MODULE_RG_ZERO_CONFIGURATION 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3202 */
#define MODULE_RG_ADVANCED_ROUTING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3207 */
#define MODULE_RG_FIREWALL_AND_SECURITY 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:119 */
#define MODULE_RG_WLAN_AND_ADVANCED_WLAN 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:67 */
#define cCONFIG_HW_ETH_WAN 1
#define CONFIG_HW_ETH_WAN 1

#define cCONFIG_HW_ETH_WAN_BLOCKED 0

#define cCONFIG_HW_CABLE_WAN 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:68 */
#define cCONFIG_HW_DSL_WAN 1
#define CONFIG_HW_DSL_WAN 1

#define cCONFIG_HW_HSS_WAN 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3279 */
#define cCONFIG_HW_ETH_LAN 1
#define CONFIG_HW_ETH_LAN 1

#define cCONFIG_HW_80211G_BCM43XX 0

#define cCONFIG_HW_USB_RNDIS 0

#define cCONFIG_HW_USB_HOST_UHCI_FEATURE 0

#define cCONFIG_HW_USB_HOST_EHCI_FEATURE 0

#define cCONFIG_HW_PCMCIA_CARDBUS_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3277 */
#define cCONFIG_HW_LEDS_FEATURE 1
#define CONFIG_HW_LEDS_FEATURE 1
#define CONFIG_HW_LEDS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1807 */
#define CONFIG_HW_BLUETOOTH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3276 */
#define cCONFIG_HW_BUTTONS_FEATURE 1
#define CONFIG_HW_BUTTONS_FEATURE 1
#define CONFIG_HW_BUTTONS_MODULE 1

#define cCONFIG_HW_CLOCK 0

#define cCONFIG_HW_IDE 0

#define cCONFIG_HW_I2C 0

#define cCONFIG_HW_ENV_MONITOR 0

#define cCONFIG_HW_ST_20190 0

#define cCONFIG_RG_FLASH_ONLY_ON_BOOT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:341 */
#define cCONFIG_RG_MAC_CLONING 1
#define CONFIG_RG_MAC_CLONING 1

#define cCONFIG_RG_WLAN_REPEATING 0

#define cCONFIG_RG_WDS_CONN_NOTIFIER_FEATURE 0

#define cCONFIG_RG_UNCONFIGURED_WAN_INTERCEPTION 0

#define cCONFIG_RG_STATISTICS_CTRL_WBM 0

#define cCONFIG_RG_WLAN_STA_STATISTICS_WBM 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:210 */
#define cCONFIG_RG_CHECK_BAD_REBOOTS 1
#define CONFIG_RG_CHECK_BAD_REBOOTS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:106 */
#define cCONFIG_RG_BLUETOOTH 1
#define CONFIG_RG_BLUETOOTH 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:107 */
#define cCONFIG_RG_BLUETOOTH_DEBUG_TOOLS 1
#define CONFIG_RG_BLUETOOTH_DEBUG_TOOLS 1

#define cCONFIG_BLUEZ_FEATURE 0

#define cCONFIG_BLUEZ_L2CAP_FEATURE 0

#define cCONFIG_BLUEZ_SCO_FEATURE 0

#define cCONFIG_BLUEZ_RFCOMM_FEATURE 0

#define cCONFIG_BLUEZ_BNEP_FEATURE 0

#define cCONFIG_BLUEZ_HCIUSB_FEATURE 0

#define cCONFIG_BLUEZ_HCIUART_FEATURE 0

#define cCONFIG_BLUEZ_HCIVHCI_FEATURE 0

#define cCONFIG_BLUEZ_HCIBTUART_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2841 */
#define cCONFIG_BT_FEATURE 1
#define CONFIG_BT_FEATURE 1
#define CONFIG_BT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2842 */
#define cCONFIG_BT_L2CAP_FEATURE 1
#define CONFIG_BT_L2CAP_FEATURE 1
#define CONFIG_BT_L2CAP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2844 */
#define cCONFIG_BT_SCO_FEATURE 1
#define CONFIG_BT_SCO_FEATURE 1
#define CONFIG_BT_SCO 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2843 */
#define cCONFIG_BT_RFCOMM_FEATURE 1
#define CONFIG_BT_RFCOMM_FEATURE 1
#define CONFIG_BT_RFCOMM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2846 */
#define cCONFIG_BT_BNEP_FEATURE 1
#define CONFIG_BT_BNEP_FEATURE 1
#define CONFIG_BT_BNEP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2847 */
#define CONFIG_BT_BNEP_MC_FILTER 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2848 */
#define CONFIG_BT_BNEP_PROTO_FILTER 1

#define cCONFIG_BT_HCIUSB_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1820 */
#define cCONFIG_BT_HCIUART_FEATURE 1
#define CONFIG_BT_HCIUART_FEATURE 1
#define CONFIG_BT_HCIUART_MODULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1821 */
#define CONFIG_BT_HCIUART_H4 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1822 */
#define CONFIG_BT_HCIUART_BCSP 1

#define cCONFIG_BT_HCIVHCI_FEATURE 0

#define cCONFIG_BT_HCIBTUART_FEATURE 0

#define cCONFIG_RG_BLUETOOTH_REQUIRES_MAC 0

#define cCONFIG_RG_BLUETOOTH_PAN 0

#define cCONFIG_RG_OBEX 0

#define cCONFIG_RG_CTP 0

#define cCONFIG_RG_CTP_VOIP_EMULATOR 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3321 */
#define CONFIG_RG_INITFS_RAMFS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2541 */
#define CONFIG_RG_MAINFS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3322 */
#define CONFIG_RG_MAINFS_CRAMFS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2574 */
#define CONFIG_RG_CRAMFS_COMP_METHOD lzma
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_target_os.c:147 */
#define CONFIG_RG_KERNEL_COMP_METHOD lzma
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:2668 */
#define CONFIG_RG_LZMA_COMPRESSED_KERNEL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:204 */
#define CONFIG_RG_LICENSE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/config_host.c:389 */
#define cLIBC_IN_TOOLCHAIN 1
#define LIBC_IN_TOOLCHAIN 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/hw_config.c:1836 */
#define cCONFIG_RG_FFS 1
#define CONFIG_RG_FFS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:48 */
#define CONFIG_SAGEM_QOS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:42 */
#define CONFIG_SAGEM_EMBEDDED_BINARIES 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:20 */
#define CONFIG_SAGEM_AUTOM_LBV1 1

#define cCONFIG_SAGEM_AUTOM_FAKE_FEATURE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:21 */
#define CONFIG_SAGEM_UMA 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:25 */
#define CONFIG_SAGEM_TRACEABILITY 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:26 */
#define CONFIG_SAGEM_FU_SAGEM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:27 */
#define CONFIG_SAGEM_CPEALIVE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:28 */
#define CONFIG_SAGEM_PROV 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:29 */
#define CONFIG_SAGEM_PARAM_REQUEST 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:30 */
#define CONFIG_SAGEM_PROC_MOD 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3326 */
#define CONFIG_SAGEM_FLASHINFOS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:37 */
#define CONFIG_SAGEM_VOICE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:38 */
#define CONFIG_SAGEM_GEN_VOICE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:46 */
#define CONFIG_SAGEM_H323 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:47 */
#define CONFIG_SAGEM_TEST_PHONE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:32 */
#define CONFIG_SAGEM_RTP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:31 */
#define CONFIG_SAGEM_RELAY 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3328 */
#define CONFIG_SAGEM_TIMEZONE_FR 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:111 */
#define CONFIG_SAGEM_LIVEZOOM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:40 */
#define cCONFIG_SAGEM_EZPAIRING 1
#define CONFIG_SAGEM_EZPAIRING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:39 */
#define CONFIG_SAGEM_LIBUTILS 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:34 */
#define CONFIG_SAGEM_USB_HOST 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:35 */
#define CONFIG_SAGEM_USB_DECT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:36 */
#define cCONFIG_THOMSON_USB_DECT 1
#define CONFIG_THOMSON_USB_DECT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3306 */
#define CONFIG_LIVEBOX_CGISCRIPT 1

#define cCONFIG_SAGEM_WIFICOMMUNITY 0

#define cCONFIG_SAGEM_IPCONF 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:23 */
#define CONFIG_SAGEM_PHONE_APP 1

#define cCONFIG_SAGEM_SENACF 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:73 */
#define CONFIG_SAGEM_OPENSSL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:8 */
#define CONFIG_SAGEM_LBV2ULT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:7 */
#define CONFIG_SAGEM_FTTHV2 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:6 */
#define CONFIG_SAGEM_GENERIC_CARD_SUPPORT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:107 */
#define cCONFIG_SAGEM_GUI_ADSL_CONFIGURATION 1
#define CONFIG_SAGEM_GUI_ADSL_CONFIGURATION 1

#define cCONFIG_SAGEM_GUI_SET_PPPO_FROM_INTERNET_ACCESS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:9 */
#define CONFIG_SAGEM_GPIO_BOXER_FOR_ULT_FW 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:12 */
#define CONFIG_SAGEM_FTTH_V2_STEP2 1

#define cCONFIG_SAGEM_GUI_DUMP 0

#define cCONFIG_SAGEM_GUI_CFG_LINE_PVC 0

#define cCONFIG_SAGEM_GUI_CFG_LINE_CLIP 0

#define cCONFIG_SAGEM_GUI_CFG_LINE_ADV_PPPOA 0

#define cCONFIG_SAGEM_GUI_CFG_LINE_ADV_PPPOE 0

#define cCONFIG_SAGEM_GUI_CFG_LINE_ADV_L2TP 0

#define cCONFIG_SAGEM_GUI_CFG_LINE_ADV_CLIP 0

#define cCONFIG_SAGEM_GUI_CFG_LINE_ADV_BRIDGE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:64 */
#define cCONFIG_SAGEM_DEVICE_DISCOVERY 1
#define CONFIG_SAGEM_DEVICE_DISCOVERY 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:86 */
#define cCONFIG_SAGEM_BACKUP_RESTORE 1
#define CONFIG_SAGEM_BACKUP_RESTORE 1

#define cCONFIG_SAGEM_BACKUP_RESTORE_DEBUG 0

#define cCONFIG_FTTH_DEFAULT 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:72 */
#define CONFIG_SAGEM_DUAL_AF_REBOOT_ON_CHANGE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:71 */
#define CONFIG_LIVEBOX_DUAL_ADSL_FTTH 1

#define cCONFIG_LIVEBOX_DUAL_PPPOA_PPPOE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:3126 */
#define cCONFIG_LIVEBOX_PERM_PARAMS 1
#define CONFIG_LIVEBOX_PERM_PARAMS 1

#define cCONFIG_SAGEM_GUI_IPSEC 0

#define cCONFIG_SAGEM_GUI_EASY_IPSEC 0

#define cCONFIG_SAGEM_DEVICE_DISCOVERY_COMPANY 0

#define cCONFIG_SAGEM_HDD_LOCAL 0

#define cCONFIG_SAGEM_GUI_FAX 0

#define cCONFIG_SAGEM_GUI_HARDDISK 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:128 */
#define cCONFIG_SAGEM_GUI_WIFI_ENERGY 1
#define CONFIG_SAGEM_GUI_WIFI_ENERGY 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:16 */
#define cCONFIG_LIVEBOX_WIFI 1
#define CONFIG_LIVEBOX_WIFI 1

#define cWIFI_ATH 0

#define cWIFI_ATH_N 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:15 */
#define cWIFI_ATH_GN 1
#define WIFI_ATH_GN 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:18 */
#define cCONFIG_SAGEM_GUI_WIFI_BG_MIXED 1
#define CONFIG_SAGEM_GUI_WIFI_BG_MIXED 1

#define cCONFIG_SAGEM_GUI_WIFI_G_ONLY 0

#define cCONFIG_SAGEM_GUI_WIFI_B_ONLY 0

#define cCONFIG_SAGEM_GUI_WIFI_BGN_MIXED 0

#define cCONFIG_SAGEM_GUI_WIFI_WEP64 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:19 */
#define cCONFIG_SAGEM_GUI_WIFI_WPAxAUTO_AES_TKIP 1
#define CONFIG_SAGEM_GUI_WIFI_WPAxAUTO_AES_TKIP 1

#define cCONFIG_SAGEM_GUI_WIFICOMMUNITY 0

#define cCONFIG_SAGEM_GUI_VISITORACCESS 0

#define cCONFIG_SAGEM_GUI_ROUTE 0

#define cCONFIG_SAGEM_GUI_LANGUAGE 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:104 */
#define cCONFIG_SAGEM_GUI_LANG_FR 1
#define CONFIG_SAGEM_GUI_LANG_FR 1

#define cCONFIG_SAGEM_GUI_LANG_EN 0

#define cCONFIG_SAGEM_GUI_LANG_ES 0

#define cCONFIG_SAGEM_GUI_ADV_FILTER 0

#define cCONFIG_SAGEM_GUI_INFO_SYS 0

#define cCONFIG_SAGEM_GUI_RTC 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:5 */
#define cCONFIG_SAGEM_GUI_LOGIN_ENABLED 1
#define CONFIG_SAGEM_GUI_LOGIN_ENABLED 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:127 */
#define cCONFIG_SAGEM_GUI_INFOSYS_WIFI 1
#define CONFIG_SAGEM_GUI_INFOSYS_WIFI 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:108 */
#define cCONFIG_SAGEM_GUI_INFOSYS_VOIP 1
#define CONFIG_SAGEM_GUI_INFOSYS_VOIP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:109 */
#define cCONFIG_SAGEM_GUI_INFOSYS_USB 1
#define CONFIG_SAGEM_GUI_INFOSYS_USB 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:110 */
#define cCONFIG_SAGEM_GUI_INFOSYS_TV 1
#define CONFIG_SAGEM_GUI_INFOSYS_TV 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:119 */
#define cCONFIG_SAGEM_GUI_PROTO_PAT_NAT 1
#define CONFIG_SAGEM_GUI_PROTO_PAT_NAT 1

#define cCONFIG_SAGEM_GUI_PORT_TRIGGERING_ACCESS 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:121 */
#define cCONFIG_SAGEM_GUI_NAT_PAT_SCHEDULE 1
#define CONFIG_SAGEM_GUI_NAT_PAT_SCHEDULE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/dist_config.c:117 */
#define CONFIG_SAGEM_GUI_NOT_USED_CODE 1

#define cCONFIG_SAGEM_GUI_DEBUG 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:103 */
#define cCONFIG_SAGEM_GUI_WARNING 1
#define CONFIG_SAGEM_GUI_WARNING 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:104 */
#define cCONFIG_SAGEM_GUI_ERROR 1
#define CONFIG_SAGEM_GUI_ERROR 1

#define cCONFIG_SAGEM_GUI_HW_DEBUG 0

#define cCONFIG_SAGEM_GUI_TV_MULTI_DECODERS 0

#define cCONFIG_SAGEM_FLASH_LAYOUT_LBV2STD 0

#define cCONFIG_SAGEM_FLASH_LAYOUT_LBV2MINI 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:10 */
#define cCONFIG_SAGEM_FLASH_LAYOUT_LBV2ULT 1
#define CONFIG_SAGEM_FLASH_LAYOUT_LBV2ULT 1

#define cCONFIG_SAGEM_FLASH_LAYOUT_LBV2BABY 0
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/feature_config.c:1149 */
#define cCONFIG_SAGEM_DSA_HDR 1
#define CONFIG_SAGEM_DSA_HDR 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:88 */
#define cCONFIG_SAGEM_CLI_RG_CONF_PRINT 1
#define CONFIG_SAGEM_CLI_RG_CONF_PRINT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:89 */
#define cCONFIG_SAGEM_CLI_RG_CONF_SET 1
#define CONFIG_SAGEM_CLI_RG_CONF_SET 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:90 */
#define cCONFIG_SAGEM_CLI_RG_CONF_SET_OBSCURE 1
#define CONFIG_SAGEM_CLI_RG_CONF_SET_OBSCURE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:91 */
#define cCONFIG_SAGEM_CLI_RG_CONF_DEL 1
#define CONFIG_SAGEM_CLI_RG_CONF_DEL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:92 */
#define cCONFIG_SAGEM_CLI_RG_CONF_PRIV_SET 1
#define CONFIG_SAGEM_CLI_RG_CONF_PRIV_SET 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:93 */
#define cCONFIG_SAGEM_CLI_RG_CONF_PRIV_PRINT 1
#define CONFIG_SAGEM_CLI_RG_CONF_PRIV_PRINT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:94 */
#define cCONFIG_SAGEM_CLI_RG_CONF_PRIV_DEL 1
#define CONFIG_SAGEM_CLI_RG_CONF_PRIV_DEL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:95 */
#define cCONFIG_SAGEM_CLI_RG_CONF_RAM_SET 1
#define CONFIG_SAGEM_CLI_RG_CONF_RAM_SET 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:96 */
#define cCONFIG_SAGEM_CLI_RG_CONF_RAM_PRINT 1
#define CONFIG_SAGEM_CLI_RG_CONF_RAM_PRINT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:97 */
#define cCONFIG_SAGEM_CLI_RG_CONF_RAM_DEL 1
#define CONFIG_SAGEM_CLI_RG_CONF_RAM_DEL 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:98 */
#define cCONFIG_SAGEM_CLI_RECONF 1
#define CONFIG_SAGEM_CLI_RECONF 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:99 */
#define cCONFIG_SAGEM_CLI_FLASH_LAYOUT 1
#define CONFIG_SAGEM_CLI_FLASH_LAYOUT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:100 */
#define cCONFIG_SAGEM_CLI_FLASH_DUMP 1
#define CONFIG_SAGEM_CLI_FLASH_DUMP 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:101 */
#define cCONFIG_SAGEM_CLI_FLASH_COMMIT 1
#define CONFIG_SAGEM_CLI_FLASH_COMMIT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:102 */
#define cCONFIG_SAGEM_CLI_FLASH_ERASE 1
#define CONFIG_SAGEM_CLI_FLASH_ERASE 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:55 */
#define CONFIG_SAGEM_RECONF 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:54 */
#define CONFIG_SAGEM_GENAUTOM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:59 */
#define CONFIG_SAGEM_TR69 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:61 */
#define CONFIG_SAGEM_TR98 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:62 */
#define CONFIG_SAGEM_TR111 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:56 */
#define CONFIG_SAGEM_LIBTR69DM 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:53 */
#define CONFIG_SAGEM_LIBMSG 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:63 */
#define CONFIG_SAGEM_TR104_H323 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:60 */
#define CONFIG_SAGEM_LIBTR98_FT 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:58 */
#define CONFIG_SAGEM_TR69API 1
/* /home/p778094/devbis/kernel/4.3.14/lastcheckout/rg/pkg/build/sagem_on_the_fly_dist_config.c:57 */
#define CONFIG_SAGEM_LIBTR69FU 1
